name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew :lazyviewmodels:build
